web/router.ex
defmodule Splurty.Router do
  use Splurty.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Splurty do
    pipe_through :browser # Use the default browser stack

    # get "/", PageController, :index
    get "/", QuoteController, :homepage
    resources "/quotes", QuoteController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Splurty do
  #   pipe_through :api
  # end
end

lib/splurty/endpoint.ex
defmodule Splurty.Endpoint do
  use Phoenix.Endpoint, otp_app: :splurty

  socket "/socket", Splurty.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :splurty, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_splurty_key",
    signing_salt: "EGrX3cJ1"

  plug Splurty.Router
end

lib/splurty/repo.ex
defmodule Splurty.Repo do
  use Ecto.Repo, otp_app: :splurty
end

web/models/quote.ex
defmodule Splurty.Quote do
  use Splurty.Web, :model

  import Ecto.Query
  alias Splurty.Repo
  alias Splurty.Quote

  schema "quotes" do
    field :saying, :string
    field :author, :string

    timestamps
  end

  @required_fields ~w(saying author)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end

  def random do
    hd from(q in Quote, select: q, limit: 1, order_by: fragment("RANDOM()")) |> Repo.all
  end
end

web/controllers/page_controller.ex
defmodule Splurty.PageController do
  use Splurty.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/error_view.ex
defmodule Splurty.ErrorView do
  use Splurty.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Splurty.LayoutView do
  use Splurty.Web, :view
end

web/views/page_view.ex
defmodule Splurty.PageView do
  use Splurty.Web, :view
end

web/views/quote_view.ex
defmodule Splurty.QuoteView do
  use Splurty.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Splurty!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/home.css") %>">
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
  </head>

  <body class="site">
    <div class="container">
      <header>
        <div class="col-xs-6">
          <div class="circle">
            <br />
            Elixir &
            <br />
            Erlang
            <br />
            Rock!
          </div>
        </div>

        <div class="col-xs-6 text-right">
          <a href="<%= quote_path(@conn, :new) %>">Contribute</a>
        </div>
      </header>

      <hr class="clear col-xs-12"/>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main" class="site-content">
        <%= render @view_module, @view_template, assigns %>
      </main>

      <footer>
        <div class="col-xs-6">
          <a href="<%= quote_path(@conn, :homepage)%>">
            This isn't enough, I need more
          </a>
        </div>
        <div class="col-xs-6 text-right">
          <a href="http://elixir-lang.org">
            <img src="/images/logo.png"/>
          </a>
          <a href="http://www.phoenixframework.org/">
            <img src="/images/poweredby-phoenix-badge1-01.png" />
          </a>
        </div>
      </footer>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="<%= static_path(@conn, "/js/jquery.restfulizer.js") %>"></script>
    <script>
      $(function() {
        $(".rest").click(function(d) {
          $('form').submit(function(s) {
            var input = $("<input>")
            .attr("type", "hidden")
            .attr("name", "_csrf_token").val("<%= get_csrf_token() %>");
            $(s.target).append($(input));
          });
        });
        $(".rest").restfulizer({});
      });
    </script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/quote/edit.html.eex
<div class="col-xs-10 col-xs-offset-1">
  <h1>Edit Quote</h1>
  <form action="<%= quote_path(@conn, :update, @quote.id) %>" method="post">
    <div class="form-group">
      <input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>">
      <input type="hidden" name="_method" value="put">

      <label for="quote[saying]">saying</label>
      <input type="text" name="quote[saying]" class="form-control" value="<%= @quote.saying %>" />

      <label for="quote[author]">author</label>
      <input type="text" name="quote[author]" class="form-control" value="<%= @quote.author %>" />

    </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>

web/templates/quote/homepage.html.eex
Number of reasons I yolo everyday <%= 10 + 14 %>

web/templates/quote/index.html.eex
<div class="page-content col-xs-10 col-xs-offset-1">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Saying</th>
        <th>Author</th>
        <th>Actions</th>
      </tr>
    </thead>
    <%= for quote <- @quotes do %>
    <tr>
      <td>
        <a href="<%= quote_path(@conn, :show, quote.id) %>">
          <%= quote.saying %>
        </a>
      </td>
      <td>
        <%= quote.author %>
      </td>
      <td>
        <a href="<%= quote_path(@conn, :edit, quote.id) %>" class="btn btn-danger">
          Edit
        </a>
        <a href="<%= quote_path(@conn, :delete, quote.id) %>" class="rest btn btn-danger" data-method="DELETE">
          Destroy
        </a>
      </td>
    </tr>
    <% end %>

  </table>
</div>

web/templates/quote/new.html.eex
<div class="col-xs-10 col-xs-offset-1">
  <h1>New Quote</h1>
  <form action="<%= quote_path(@conn, :create) %>" method="post">
    <input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>">
    <div class="form-group">
      <label for="quote[saying]">saying</label>
      <input type="text" name="quote[saying]" class="form-control" />

      <label for="quote[author]">author</label>
      <input type="text" name="quote[author]" class="form-control" />

    </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
</div>

web/templates/quote/show.html.eex
<div class="col-xs-10 col-xs-offset-1 page-content">
  <h3>
    <span>SPLURTY No. <%= @quote.id %></span>
    You know <u>you need to learn Elixir</u> because...
  </h3>
  <h1>
    <%= @quote.saying %>
  </h1>

  <h2 class="text-right">
    <%= @quote.author %>
  </h2>
</div>